ALTER TABLE t_p16564901_site_launch_bot.orders
  ADD COLUMN IF NOT EXISTS tg_message_id BIGINT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS payment_id VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS payment_url TEXT DEFAULT NULL;
